# Created with YamlCreate.ps1 v2.4.1 $debug=NVS1.CRLF.5-1-19041-4780.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: RITE.VEXOTControl
PackageVersion: 1.10.51
InstallerLocale: en-US
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT
  SilentWithProgress: /SILENT
  Custom: /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Commands:
- vexotcontrol
ReleaseDate: 2024-09-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AndreiBee/VEXOTControl/releases/download/v1.10.51/VEXOTControlInstaller_v1.10.51.exe
  InstallerSha256: 6EC93BC5C0CE8DB5079E5ECEF7A333DE95068C2080622068B1265B55E75BAF52
ManifestType: installer
ManifestVersion: 1.6.0
