Id: RITE.VEXOTControl   # A unique identifier for your app, typically in the format CompanyName.AppName
Name: VEXOTControl             # The display name of your application
Publisher: RITE      # The name of your company
Version: 1.10.46                 # The version number of your application
License: Proprietary              # The license type (e.g., MIT, GPL, Proprietary)
LicenseUrl: https://www.gnu.org/licenses/gpl-3.0.txt  # URL to your license terms
InstallerType: exe                # Type of installer (e.g., exe, msi)
InstallerUrl: https://github.com/AndreiBee/VEXOTControl/releases/download/v1.10.47/VEXOTControlInstaller_v1.10.47.exe  # Direct download link to your installer
InstallerSha256: [2595EFC8D0DB9F213F4F0412C3CF9E5BA9A65E2B6859C91B7C900395F077960B]  # The SHA256 hash of the installer
Installers:                       # This section allows you to specify different installers for different architectures or package types
  - Architecture: x64
    InstallerUrl: https://github.com/AndreiBee/VEXOTControl/releases/download/v1.10.47/VEXOTControlInstaller_v1.10.47.exe
    InstallerSha256: [2595EFC8D0DB9F213F4F0412C3CF9E5BA9A65E2B6859C91B7C900395F077960B]
Description: VEXOTControl is a tool for controlling camera devices.  # A brief description of your application
Homepage: https://github.com/AndreiBee/VEXOTControl  # URL to your application's homepage